SELECT ROUND(SUM(TIV_2016),2)
 AS tiv_2016 FROM INSURANCE I
WHERE TIV_2015 IN (SELECT DISTINCT TIV_2015 FROM INSURANCE WHERE PID!=I.PID) AND
(LAT,LON) NOT IN (SELECT LAT,LON FROM INSURANCE WHERE LAT=I.LAT AND LON=I.LON AND PID!=I.PID)